### ISSUE TITLE
Frontend: Abonnieren zu und Deabonnieren von Mailgruppen

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-newsletter#1]
Beliebige User sollen eine EIngabemaske bekommen (diese kann auch mit Acess-Controll geschützt sein) um sich zu Listen, die dazu öffentlich freigegeben wurde anzumelden. 
 Oder wenn sie Mitglied sind um sich davon abzumelden.

**Comment by xwolfde** [comment]
Sollten wir hier dennoch anbieten können:
Ein Formular, welches eine entsprechend formatierte E-Mail mit dem (un)subscribe-Befehl an den Mailman sendet.

Die Mailman-Oberfläche wird von Kunden als nicht benutzerfreundlich  angesehen.

**Comment by rvdforst** [comment]
Das Plugin enthält ein eigenes Newsletter-Anmeldeformular (Opt-In/-Out). Dies gilt nicht für Funktionsaddressen, bei denen es sich um externe Dienste handelt, die ihre eigenen Abonnementmechanismen anbieten. Meiner Meinung nach liegt die Implementierung von Abonnementmechanismen für Funktionsaddresen außerhalb des Zwecks dieses Plugins.
