### ISSUE TITLE
Sendezeiträume: Wiederkehrende, automatische Sendungen

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-newsletter#10]
Aktuell gibt es die Box "Mail-Einstellungen" in der auch das Sende Datum /Uhrzeit" ist.

Das Sendedatum würde ich in eine eigene Box auslagern, in der man die Sendezeit(en) eingeben kann.

Dazu kommt, dass neben einer einmaligen Aussendung auch eine automatisch wiederholende Aussendung ermöglicht wird.
Hierzu muss es dann entsprechende Auswahlmöglichkeiten geben um die Zeit der wiederholten Termine zu steuern.

Da wiederholbare Termine nur sinnvoll sind, wenn der Content  jeweils neu gemacht wird, sollte diese Option ggf. an Vorlagen verknüpft werden, die auch automatisch erzeugten Content haben (wie bspw. Posts).

**Comment by rvdforst** [comment]
Seit Version 1.5
