### ISSUE TITLE
Post-Inserter für individuelle Beiträge wirft Fehlermeldung 

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/rrze-newsletter#106]
Ich möchte neben Bild und Textabschnitten, die ich selbst formuliere, auch noch Infos aus der Seite „Aktuelles“ von unserer Homepage einfügen. Den Post Inserter habe ich entdeckt. Wenn ich ihn betätige, kann ich die Anzahl der Posts auswählen, so weit so gut. 
Ich habe es allerdings nicht geschafft, einen bestimmten Beitrag über die „Suchfunktion“ einzufügen. Dann kommt die Fehlermeldung: „In diesem Block ist ein Fehler aufgetreten und eine Vorschau ist nicht möglich.“

http://go.fau.de/9uk05

**Comment by rvdforst** [comment]
Mit der Version 2.4.0 des Plugins wurde der „Post Inserter“-Block komplett weiterentwickelt, um die UI zu verbessern. Aus Zeitgründen wird der Block kurzfristig nicht um neue Funktionen erweitert.
