### ISSUE TITLE
Content-Feldtyp: RSS 

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-newsletter#11]
Neben statischen Text und eigenen Post sollte es auch möglich sein, fremde (also von einer anderen Website) RSS einzubinden.

Für die Quelle des RSS sollte eine URL-Eingabe angeboten werden.
Filterungen wie bei Posts #8 

Ausgabe des Inhalts im Template über Felder wie

RSS-Item-Titel
RSS-Item-Description
RSS-Item-Link
RSS-Item-PubDate

Da das RSS neben den Items auch andere Felder mit geliefert werden, sollten diese dann auch in der Vorlage nutzbar sein.
Nämlich:
RSS-Titel 
RSS-Link
RSS-Language

**Comment by rvdforst** [comment]
Seit Version 1.3. Anstelle einer Vorlage wird jedoch die RSS-Block-Einstellungen verwendet.
