### ISSUE TITLE
Fehlermeldungen beim Öffnen/Entwürfe werden nicht gespeichert

### ISSUE THREAD

**Issue by wrcg** [RRZE-Webteam/rrze-newsletter#115]
Fehlermeldung beim Öffnen (als Admin), 

<img width="698" alt="image" src="https://github.com/RRZE-Webteam/rrze-newsletter/assets/9526974/603d3b35-fdbe-4d03-bd12-c9f96c188d03">

Speichern scheint nicht zu funktionieren. Ich habe einfach mal einen Testbetreff eingegeben, auf Entwurf speichern geklickt. Dann kam die gleiche Fehlermeldung von oben. 
Nach Verlassen der Seite war im Dashboard diese Übersicht
<img width="785" alt="image" src="https://github.com/RRZE-Webteam/rrze-newsletter/assets/9526974/23cd3dc3-e707-4cca-9ffe-554930c10847">

Es hat also den Testbetreff nicht gespeichert

**Comment by rvdforst** [comment]
Dieses Problem sollte inzwischen behoben sein.
