### ISSUE TITLE
 Content-Feldtyp: ical/ics-URL

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-newsletter#12]
Neben statischen Text und eigenen Post sollte es auch möglich sein, fremde (also von einer anderen Website) Kalender einzubinden.

Für die Quelle der  ical/ics-URL sollte eine URL-Eingabe angeboten werden.
Filterungen wie bei Posts #8 bzw #11

Ausgabe des Inhalts im Template über Felder wie

ICS-Item-Summary
ICS-Item-Description
ICS-Item-DTStart
ICS-Item-DTEnd

**Comment by rvdforst** [comment]
Seit Version 1.4 (ICS-Block)
