### ISSUE TITLE
RegExp/Ergänzung zu URLs in der Newsletter

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-newsletter#13]
Es soll eine Option bestehen bei einer Vorlage alle in dem Content befindliche URLs zu modifizieren oder zu ergänzen.
(Dies insbesondere auch bei automatisch generierten Content, vgl. #11 und #9 )

Die einfache Form wäre eine Ergänzung der URL durch Anhängen von Paramatern.
Bspw.:
Die Originale URL 
https://www.fau.de/corona/podcast/

wird um Parameter ergänzt und sieht dann bei der Aussendung so aus:
https://www.fau.de/corona/podcast/?utm_campaign=2021-02-24&utm_source=newsletter&utm_medium=email

**Comment by rvdforst** [comment]
Ein Teil davon ist bereits in V. 0.1.0 enthalten.

**Comment by rvdforst** [comment]
Seit Version 1.6.5
