### ISSUE TITLE
Blöcke habe keine Abstände mehr

### ISSUE THREAD

**Issue by AndiWebred** [RRZE-Webteam/rrze-newsletter#135]
Einzelne Blöcke, wie Absätze, Bilder oder Trennzeichen haben keine Abstände mehr zueinander und kleben aneinander. Das sieht im Blockeditor noch gut aus, wird die Mail versendet aber nicht mehr. Das war im Juli definitiv noch anders.

Hier ein Vergleich des gleichen Newsletters, offiziell verschickt am 3. Juli 2024 und erneuter Testversand am 15. August 2024.
Korrekte Darstellung
![Newsletter_Juli](https://github.com/user-attachments/assets/3e53e3f3-724d-48a8-83f3-b29d7c01f5c7)
Fehlerhafte Darstellung
![Newsletter_August](https://github.com/user-attachments/assets/6fbb27c2-ea5e-4af4-8f73-28efc39bd389)

Der Newsletter in Wordpress: https://www.fau.de/wp-admin/post.php?post=10316998&action=edit

**Comment by rvdforst** [comment]
Das Problem wurde bereits behoben.
