### ISSUE TITLE
Bearbeiterrolle für Newsletter

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-newsletter#15]
Es soll eine zusätzliche Bearbeiterrolle für Newsletter angelegt werden.

"Newsletter-Verwalter"

Per Default sollten die Funktionen des Newsletters für Administratoren und Redakteure freigeschaltet sein.

**Comment by rvdforst** [comment]
Es ist bereits in V. 0.1.0 enthalten. Rolle: "Newsletter-Agent" (newsletter).
