### ISSUE TITLE
Automatische Newsletter vom Content-Quelle abhängig machen

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-newsletter#16]
Wenn ein Newsletter automatisch versendet wird und sich aus einer Datenquelle (Posts, RSS, ICal) bedient, soll die Versendung davon abhängig gemacht werden, dass die Datenquelle einen Inhalt geliefert hat.
Wenn die Quellen keine (neuen) Inhalte liefern, soll der Newsletter nicht versendet werden.

**Comment by rvdforst** [comment]
Seit Version 1.5 (Conditionals).
