### ISSUE TITLE
Individuelle Permalinks für Newsletter / Kategorien

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-newsletter#17]
Die Webform aller Newsletter sollen unter dem Slug /newsletter/ abgespeichert werden.

Zusätzlich soll es jedoch möglich sein, einzelne Newsletter zu Kategorisieren um einzelne Newsletter von anderen auseinander zu halten und ein Index über die Newsletter einer Kategorie zu erhalten.

Ein Newsletter zum Thema Netzwerk sollte also beispielsweise unter /newsletter/netzwerk/  zu finden sein.

**Comment by rvdforst** [comment]
Dies ist bereits in V. 0.1.0 möglich.
