### ISSUE TITLE
Unausgefüllte Felder sollen nicht angezeigt werden

### ISSUE THREAD

**Issue by AndiWebred** [RRZE-Webteam/rrze-newsletter#19]
Bei einer Vorlage mit beispielsweise 5 Text-areas werden auch immer diese 5 areas angezeigt, selbst wenn eine davon leer ist. Es erscheint dann eine Leerzeile. Es wäre praktisch, wenn leere Felder aber gar nicht ausgegeben werden. So wären Newsletter-Bearbeiter flexibler in der Gestaltung.

**Comment by rvdforst** [comment]
Im Gegensatz zum Plugin "Greetings" können in diesem Plugin nur vordefinierte Variablen (TAGS) in Newslettern verwendet werden. TAGS, die keinen Wert enthalten, werden im gerenderten Newsletter nicht angezeigt. Mehr dazu in der README-Datei: https://github.com/RRZE-Webteam/rrze-newsletter/blob/dev/README.md
