### ISSUE TITLE
Deklaration von Adressatengruppe als Öffentlich

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-newsletter#2]
Versandlisten sollen vom Admin mit einem Status (Öffentlich oder Privat) versehen werden können.
Besucher der Website sollen öffentliche Listen für ein Abonnieren auswählen können. Vgl RRZE-Webteam/rrze-newsletter#1 
Hierzu sollte auch jede Liste mit einem erklärenden Text ergänzt werden.

**Comment by rvdforst** [comment]
Diese Funktion ist bereits in Version 0.2.0 vorhanden.
