### ISSUE TITLE
Versand-Datum im Newsletter anzeigen

### ISSUE THREAD

**Issue by AndiWebred** [RRZE-Webteam/rrze-newsletter#20]
Es sollte möglich sein, das Versand-Datum im Newsletter anzuzeigen. Das ginge momentan (soweit ich das sehe) nur mit einem Extra-Feld, das ausgefüllt werden muss.

**Comment by xwolfde** [comment]
Außerdem:
Daten des verwendeten Mailverteilers. Titel, Link, Link aufs Archiv. Ggf. Subscripte- und Unsubscripe Optionen?

**Comment by rvdforst** [comment]
Im Gegensatz zum Plugin "Greetings" können in diesem Plugin nur vordefinierte Variablen (TAGS) in Newslettern verwendet werden. Der TAG des Versanddatums ist {{= DATE}}. Mehr dazu in der README-Datei: https://github.com/RRZE-Webteam/rrze-newsletter/blob/dev/README.md
