### ISSUE TITLE
Flexible Gestaltung ermöglichen

### ISSUE THREAD

**Issue by AndiWebred** [RRZE-Webteam/rrze-newsletter#21]
Sehr praktisch wäre es, wenn man ganze Abschnitte (also eine Einheit aus Bild, Überschrift, Text und Link) verschieben könnte, um die Reihenfolge von Abschnitten anzupassen.

**Comment by xwolfde** [comment]
Erweiterte Funktion für den limitierten Einsatz des Plugins bei SPuK.

Einsatz von Block-Editor Funktionalität

**Comment by rvdforst** [comment]
Dies ist bereits in V. 0.1.0 möglich.
