### ISSUE TITLE
Übername alle Funktionalitäten des Plugins RRZE-Greetings

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-newsletter#22]
Alle Funktionen und Features des Greetings-Plugins sollen übernommen werden.

**Comment by rvdforst** [comment]
Dies ist nicht ganz möglich, da dieses Plugin ausschließlich auf dem Blockeditor basiert.

**Comment by rvdforst** [comment]
In jedem Fall wurden viele Funktionen des Greetings-Plugins für den Blockeditor angepasst.
