### ISSUE TITLE
Im Browser ansehen auch im Browser :=)

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-newsletter#29]
Wenn ich einen Beitrag "im Browser" ansehe, erscheint dort auch de Link "Im Browser ansehen".

![grafik](https://user-images.githubusercontent.com/1070669/118960755-22ab2e00-b953-11eb-8abe-6c08a867170e.png)

Stattdessen wäre es gut, wenn man dort auf den Custom Post Type Index/Archiv verlinkt wird.

**Comment by rvdforst** [comment]
Um dies zu vermeiden, sollte der TAG `{{EMAIL_ONLY}}` verwendet werden. Bspw.
`{{EMAIL_ONLY}}IM BROWSER ANZEIGEN{{/EMAIL_ONLY}}`
