### ISSUE TITLE
Template-Portfolio für Newsletter

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-newsletter#3]
Neben dem vorhandenen MLM-Template sollten wietere Templates zur Auswahl bereit gestellt werden.

Und zwar:
* Vorlage für Grußkarte (vorhanden)
* Vorlage für Aktuelle Meldungen
* Vorlage für eine Sondermeldung, die wie eine aktuelle Meldung ist, aber besonders hervorgehoben ist

**Comment by rvdforst** [comment]
Dies ist bereits in V. 0.1.0 möglich. Hierzu wird das CPT "newsletter_layout" verwendet. Die Layouts werden im JSON-Format gespeichert. Hinweis: Der verwendete Begriff ist Layout (anstelle von Template), da es sich um vom Blockeditor generierten Inhalt handelt.
