### ISSUE TITLE
FAU-Mailverteiler als einzigen Default Empfänger

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-newsletter#31]
Bei Erstellung eines neuen Newsletter sollte als Default erstmal als "Empfänger" eine Mailadresse eines (1) FAU-Mailverteilers (in der Regel auch mit @fau.de Absenderadresse) erfragt werden.

In dem Fall wird auch die ganze Abo/Deabo-Funktionalität deaktiviert bzw. privat gesetzt sein.

Erst wenn man ausdrücklich irgendwo ein Haken setzt wie "Eigenen Verteiler mit Empfänger anlegen" , dann sollen die bisherigen Abo-Funktionen eingeschaltet werden.

**Comment by rvdforst** [comment]
v1.2.0 (Wird von Hooks gesteuert).
