### ISSUE TITLE
Mail-Einstellung zum Rate-Limit bei FAU-Einsatz deaktivieren

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-newsletter#32]
Wenn das Plugin an der FAU eingesetzt wird für Mailadressen der FAU, sollen Einstellungen zum Rate-Limit durch den Webmaster nicht änderbar sein

**Comment by rvdforst** [comment]
v1.2.0 (Wird von Hooks gesteuert).
