### ISSUE TITLE
Abo-Funktionalität beschränken

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-newsletter#33]
Die Abo-Funktionalität bei Standard-CMS-Instanzen abschalten; Nur die Möglichkeit eröffnen, eine Mailadresse (=Mailverteileradresse) einzutragen.

Die Abo-Funktionalitäten nur über ein Superadmin-Setting aktivierbar machen.

**Comment by xwolfde** [comment]
Siehe auch #31

**Comment by rvdforst** [comment]
v1.2.0 (Wird von Hooks gesteuert).
