### ISSUE TITLE
Gutenbergbuttons können die Mail-Darstellung zerschießen

### ISSUE THREAD

**Issue by ej64ojyw** [RRZE-Webteam/rrze-newsletter#38]
Beim versenden der Test-Mails sind Darstellungsfehler mit dem Gutenberg-Button aufgetaucht:

Meine Vermutung: Full-width verursacht die Probleme 
Bsp-Layout auf Huts-Dev zu finden. (Habs abgespeichert)

Beispiele der probl. Darstellung:
Microsoft Mail (Vorinstallierte Standard-Mail-App)
Problem: Button verliert Textfarbe
![issue microsoft mail](https://user-images.githubusercontent.com/58593037/123396799-088feb80-d5a2-11eb-899f-3091d8725322.png)

GMAIL (gmail.com)
Buttoneinstellung: 100% width (scheint allgemein Probleme zu verursachen) & in 50% Spalte gesetzt:
Problem: Darstellung des Buttons wird einzeilig und verläuft vertikal:
![grafik](https://user-images.githubusercontent.com/58593037/123395429-7a673580-d5a0-11eb-878c-80c664ed960d.png)

Darstellung auf mobilen Endgeräten rendert Buttons ohne full-width, trotzdem korrekt
![20210625_082028548_iOS](https://user-images.githubusercontent.com/58593037/123395535-9965c780-d5a0-11eb-88c6-32bd6c88000b.png)
![20210625_082118485_iOS](https://user-images.githubusercontent.com/58593037/123395538-99fe5e00-d5a0-11eb-958a-404a3e0d67ce.png)

**Comment by rvdforst** [comment]
Fixed! (dev branch)
