### ISSUE TITLE
Default Vorlagen automatisch importieren und nicht änderbar machen

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-newsletter#4]
Die Default-Vorlagen sollen automatisch als Standardvorlage angelegt werden; Das Importieren unter Einstellungen soll daher dort entfallen.

Dafür sollen diese Defaultvorlagen nicht änderbar sein.

(Zur Änderung muss man die Vorlagen kopieren können.)

**Comment by rvdforst** [comment]
Version 0.1.0 enthält ein verbessertes System zur Verwaltung von Layouts (Vorlagen).
