### ISSUE TITLE
Hintergrundfarbe einzelner Blöcke anpassen

### ISSUE THREAD

**Issue by AndiWebred** [RRZE-Webteam/rrze-newsletter#44]
Es ist eigentlich bereits möglich, einzelnen Blöcken (Headlines, Paragraphs, usw.) eine eigene Hintergrundfarbe zu geben. Das funktioniert aber nicht für alle Farben.

Getestet habe ich es mit blau, weiß und gelb. Funktioniert hat nur blau. Weiß und gelb wurden in der Mail nicht übernommen. Weiß ist zum Beispiel dann nötig, wenn ich der gesamten Mail eine Hintergrundfarbe gebe.

**Comment by rvdforst** [comment]
Wurde behoben (V. 1.5.4)
