### ISSUE TITLE
Schriftfarbe für einzelne Blöcke anpassen

### ISSUE THREAD

**Issue by AndiWebred** [RRZE-Webteam/rrze-newsletter#45]
Es ist eigentlich schon möglich die Schriftfarbe für einzelne Blöcke (Headlines, Paragraphs, usw.) anzupassen. Die Schriftfarbe wird aber nicht in der Mail übernommen.

Getestet habe ich das mit weiß auf blauem Hintergrund.

Auch Links bleiben blau, selbst wenn ich eine andere Schriftfarbe angebe.

**Comment by rvdforst** [comment]
Wurde behoben.
