### ISSUE TITLE
Anker-Links setzen

### ISSUE THREAD

**Issue by AndiWebred** [RRZE-Webteam/rrze-newsletter#46]
Für lange Newsletter sollte es die Möglichkeit geben Anker-Links zu setzen. Wir machen das in unseren FAU-Newsletter so.
Bisher habe ich keine Lösung gefunden, dass das auch hier funktioniert. Ich habe IDs vergeben und darauf mit `<a href>` verlinkt, aber im Mailprogramm führt der Link in die Leere.
Es gibt die Option Ankler zu definieren, aber ich weiß nicht, wie ich auf diese Anker dann verweisen soll.

**Comment by rvdforst** [comment]
Siehe https://www.wordpress.rrze.fau.de/plugins/spezialplugins/rrze-newsletter/#collapse_4
