### ISSUE TITLE
Vorlagen kopieren

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-newsletter#5]
Bestehende Vorlagen sollen kopiert werden können.

Hier müsste in den Optionen ein "Kopieren" hinzukommen:
![grafik](https://user-images.githubusercontent.com/1070669/110934028-6404d900-8325-11eb-9fb4-c452f19d0965.png)

**Comment by rvdforst** [comment]
V. 0.1.0 enthält ein verbessertes System zur Wiederverwendung von Layouts (Vorlagen).
