### ISSUE TITLE
Möglichkeit mjml-Vorlagen zu verwenden?

### ISSUE THREAD

**Issue by AndiWebred** [RRZE-Webteam/rrze-newsletter#51]
Ich weiß, wir hatten das schon mal angesprochen und die Antwort war eher zurückhaltend. Ich möchte aber dennoch der Vollständigkeit halber doch noch den Vorschlag machen, einen mjml-Vorlagen-Upload zu ermöglichen. Oder so etwas in der Art.

**Comment by rvdforst** [comment]
Z.Zt. ist es nicht möglich.
