### ISSUE TITLE
Web-Darstellung und Mail-Darstellung sollen gleich aussehen

### ISSUE THREAD

**Issue by AndiWebred** [RRZE-Webteam/rrze-newsletter#52]
Die Darstellung im Browser sollte genauso aussehen und genauso formatiert sein, wie die Darstellung im Mail-Postfach. Momentan wird vermutlich (?) noch das Webseiten-CSS über die Mail gesetzt und damit alle Formatierungen angepasst.

**Comment by rvdforst** [comment]
Muss man den Tag  {{=PERMALINK}} verwenden.
