### ISSUE TITLE
Defaultvorlagen nicht änderbar

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-newsletter#6]
Siehe #5 und #4  : Die Defaultvorlagen sollen nicht änderbar sein. Alle Felder werden dann Readonly.

Wer sie ändern möchte, muss sie kopieren (#5)

**Comment by rvdforst** [comment]
V. 0.1.0 enthält ein neues Layouts-Verwaltungssystem, das in den Blockeditor integriert ist. Neben anderen Funktionen wird das Löschen oder Bearbeiten der Standardlayouts vermieden.
