### ISSUE TITLE
Inhalt ein bisschen zu schmal. Am Handy und über Link "Im Browser öffnen" nicht lesbar

### ISSUE THREAD

**Issue by faurex** [RRZE-Webteam/rrze-newsletter#67]
Liebe Entwickler,

vorab, kann es am Gutenberg Editor liegen? Jedenfalls schaut der Inhalt über Outlook zu schmal aus und am Handy ist es unlesbar. Hier wie der Inhalt im Gutenberg Editor im Adminbereich aussieht:

![editor](https://user-images.githubusercontent.com/44059562/129869755-d2aa89a6-4c59-4893-8000-ba42ea3da8dc.png)

Hier die Ansicht vom Quellcode:

![editor code](https://user-images.githubusercontent.com/44059562/129869787-c4c950a1-2de0-49c1-bca7-d18d4ff2630f.png)

Hier das Ergebnis in Outlook:

![outlook](https://user-images.githubusercontent.com/44059562/129869825-fe2130f1-fac6-45e3-b6b7-3d9d17009778.png)

Der Link im Browser anzeigen führt zur Anzeige von reinem Text ohne jegliche formatierung, also nicht lesbar:

![image](https://user-images.githubusercontent.com/44059562/129870056-56552483-4553-4e92-8290-ec9251ce2824.png)

Und hier wie der Newsletter auf einem Android Handy im Mail Client aussieht:

![handy](https://user-images.githubusercontent.com/44059562/129870129-3d9a5df0-2b05-4580-a51d-9f2f0ea1c873.jpg)

Liebe Grüße
Andy

**Comment by rvdforst** [comment]
Ich muss gestehen, dass die Verwendung des Blockeditors (aka Gutenberg) alles andere als trivial ist. Vor allem, wenn wir den klassischen Editor gewohnt sind. Dieses Plugin stellt nur eine Teilmenge der im Blockeditor verfügbaren Blöcke dar. Einige Blöcke wurden modifiziert und andere speziell für dieses Plugin entwickelt. Der Grund dafür ist, dass nicht alle Blöcke so gerendert werden können, dass sie mit den meisten E-Mail-Clients kompatibel sind.
Bei der Erstellung eines Newsletters ist folgendes zu beachten: Die Links- und Rechtsausrichtung von Absätzen, Schaltflächen, Spalten und Gruppen sind mit einigen E-Mail-Clients nicht kompatibel. Verschachtelte Spalten werden ebenfalls nicht unterstützt.
Ich schlage vor, einen Newsletter so einfach wie möglich zu erstellen, damit er mit den meisten E-Mail-Clients kompatibel ist.

**Comment by faurex** [comment]
Danke für die schnelle Antwort. Wir haben auch kein Problem den Blockeditor (Gutenberg) nicht zu verwenden. Ich habe so ziemlich alles Optionen durchgeschaut und auch Google bemüht, aber ich finde keine Möglichkeit im Newsletter Bereich den Editor auf den klassischen Editor umzustellen. Wir haben auch das "Plugin Advanced Editor Tools (vormals TinyMCE Advanced)" aktiviert, aber der Gutenberg lässt sich leider nicht deaktivieren. Irgendwie gab es da mal eine Option. Durch die vielen Wordpress Updates in letzter Zeit kennt man sich langsam nicht mehr aus. Kannst du bitte nochmal helfen? Den Newsletter im Blockeditor möglichst einfach zu halten und das gewünschte Ergebnis zu erziehlen ist sehr schwer. Die Farben, Hintergründe und Bilder sind irgendwann nicht mehr zu ändern. Wahrscheinlich einfach zu viel verschachtelte CSS-Klassen und Codes. Das Ergebnis ist jetzt jedenfalls schon ein bisschen besser:

![Vorschaubild](https://user-images.githubusercontent.com/44059562/130438679-b566acdb-5f4c-4002-83b1-dd5334dbb47b.png)

Leider brauchen wir wirklich bitte den alten Editor im Newsletterbereich. Das würde den Prozess für uns sehr vereinfachen.

**Comment by rvdforst** [comment]
Das Plugin funktioniert nur mit dem Blockeditor. Die Gestaltung eines Newsletters ist jedenfalls nicht trivial, da es sich nicht um eine Webseite handelt. In den nächsten Tagen werde ich versuchen, neue Standardvorlagen hinzuzufügen, damit diese als Grundlage für die Erstellung eines Newsletters verwendet werden können.
