### ISSUE TITLE
Content- Feldtyp: Editor hinzufügen

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-newsletter#7]
Der Content-Teil soll neben Text und Textarea und Datei auch enthalten:

WYSWYG zum Aufruf des wp_editor bzw des Block Editors zur Gestaltung des Inhalts.
 
![grafik](https://user-images.githubusercontent.com/1070669/110934520-0329d080-8326-11eb-9f48-5511898cf052.png)

**Comment by rvdforst** [comment]
Im Gegensatz zum Plugin "Greetings" können in diesem Plugin nur vordefinierte Variablen (TAGS) in Newslettern verwendet werden. Mehr dazu in der README-Datei: https://github.com/RRZE-Webteam/rrze-newsletter/blob/dev/README.md
