### ISSUE TITLE
Content-Feldtyp: Posts - Auswahl, Filterung  

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-newsletter#8]
Es soll möglich sein ein Inhaltsbereich zu definieren, der sich automatisch aus den Posts der Website befüttert.

Zur Auswahl der Posts, die in den Newsletter aufgenommen werden soll, muss es entsprechende Filtermöglichkeiten geben.

Diese wären:

* Datumbereich:  Alle Posts der letzten X Tage/ X Wochen / X Monate
* Tags:  Posts mit dem Tag T
* Category: Posts aus der Category C

Diese 3 Filter sollen auch kombinierbar sein.
Also z.B.: alle Posts der letzten 7 Tage mit dem Tag "Netzwerk" aus der Kategorie "Wartungsmeldungen"

Sowie dazu
Mengenbegrenzung: Maximal n Posts aus dem Bereich.

**Comment by rvdforst** [comment]
Seit Version 1.1 (Post Inserter Block)
