### ISSUE TITLE
🙆‍♂️ Newsletter-Anmeldeseite erscheint standardmäßig auf der Startseite

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/rrze-newsletter#89]
Wenn keine individiuelle Newsletter-Anmeldeseite ausgewählt wurde, erscheint Sie standardmäßig auf der Startseite.
Bsp.: https://huts.dev.cms.rrze.de

**Comment by rvdforst** [comment]
bug fixed (v1.7.9)
