### ISSUE TITLE
Content-Feldtyp: Posts - Darstellung

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-newsletter#9]
Bei der Darstellung der einzelnen Posts sollen Titel, Excerpt, Content, Artikelbild berücksichtigt werden können und im Template darstellbar sein.

**Comment by rvdforst** [comment]
Seit Version 1.1. Anstelle einer Vorlage wird jedoch das Post-Inserter-Block verwendet.
