### ISSUE TITLE
Abstände sind zu groß

### ISSUE THREAD

**Issue by AndiWebred** [RRZE-Webteam/rrze-newsletter#93]
Die Abstände der einzelnen Absätze/Blöcke ist in Outlook und anderen Mail-Programmen zu groß und sollte deutlich verringert werden.

**Comment by wrcg** [comment]
Cool, bin gespannt, ob Rolf reagiert ;-) Mir hat er erklärt, dass ich im Quelltext die <p> entsprechend löschen soll, was aber leider nicht funktioniert hat…

.......................................................
Cathrin Gräf, Webredaktion

Friedrich-Alexander-Universität Erlangen-Nürnberg
Schlossplatz 4     91054 Erlangen     Germany
***@***.******@***.***>
http://www.fau.de<http://www.fau.de/>
.......................................................

Von: Andreas Dittmann ***@***.***>
Gesendet: Donnerstag, 19. Mai 2022 11:49
An: RRZE-Webteam/rrze-newsletter ***@***.***>
Cc: Subscribed ***@***.***>
Betreff: [RRZE-Webteam/rrze-newsletter] Abstände sind zu groß (Issue #93)


Die Abstände der einzelnen Absätze/Blöcke ist in Outlook und anderen Mail-Programmen zu groß und sollte deutlich verringert werden.
